### ISSUE TITLE
cannot use jquery draggable inside ember-scrollable component

### ISSUE THREAD

**Issue by ashbardanyan** [alphasights/ember-scrollable#39]
Hello

I am using jquery ui draggable inside scrollable component and it prevents my draggable elements from dragging. I have search and found the issue inside your add-on:
```
  /**
  * Drag scrollbar handle
  */
  drag(e) {
    return;
    e.preventDefault();

    this.get('scrollbar').drag(e);
  },

```
this code is preventing it from working and I guess it should not be global for entire ember-scrollable component, and you can move this to be prevented only on the handle.

Thanks
Ashot Vardanyan

**Comment by alexander-alvarez** [comment]
hey @ashbardanyan  the issue should go away as a byproduct of the https://github.com/alphasights/ember-scrollable/pull/29 refactor

**Comment by alexander-alvarez** [comment]
@ashbardanyan check with https://github.com/alphasights/ember-scrollable/releases/tag/0.4.0 to see if you still have the issue

**Comment by dknutsen** [comment]
We started running into something similar in our app when we upgraded Ember Light Table from v1.8.0 (uses ember-scrollable 0.3.5) to v1.8.2 (uses ember-scrollable 0.4.0). Meaning that I think ember-scrollable 0.4.0 is actually what is causing the problem. 

Dragging actually still works, but it throws the following error every several times a second:
```
Uncaught TypeError: this._contentElement[sizeAttr] is not a function
    at Class.contentSize (ember-scrollable.js:204)
    at Class.drag (ember-scrollable.js:452)
    at Class.trigger (ember.debug.js:44818)
    at Class.superWrapper [as trigger] (ember.debug.js:25371)
    at Backburner.join (ember.debug.js:345)
    at Function.run.join (ember.debug.js:24337)
    at ember.debug.js:45015
    at Object.flaggedInstrument (ember.debug.js:20751)
    at Object.handleEvent (ember.debug.js:45014)
    at Class.exports.default._emberMetalMixin.Mixin.create._Mixin$create.handleEvent (ember.debug.js:44034)
    at Class._bubbleEvent (ember.debug.js:44554)
    at HTMLDivElement.<anonymous> (ember.debug.js:44476)
    at HTMLBodyElement.dispatch (jquery.js:4737)
    at HTMLBodyElement.elemData.handle (jquery.js:4549)
    at HTMLBodyElement.c (raven.js:275)
```

In the code in question (below), `sizeAttr` gets passed in as undefined:
```
    contentSize: function contentSize(sizeAttr) {
      return this._contentElement[sizeAttr]();
    },
```

**Comment by alexander-alvarez** [comment]
understood -- will take a look.

**Comment by offirgolan** [comment]
@dknutsen @ashbardanyan can you both upgrade to the latest version of ELT or ember-scrollable and see if you're still facing these issues?

**Comment by dknutsen** [comment]
@offirgolan just tried it (ELT 1.8.3 w/ ember-scrollable 0.4.2), still seeing the same thing...

**Comment by offirgolan** [comment]
@dknutsen that's really weird. Im not able to recreate this at all. Any chance you can reproduce this in an ember-twiddle?

**Comment by dknutsen** [comment]
@offirgolan Looked into doing a twiddle but I'm not sure how best to replicate some of the code in a twiddle. What we're doing is kinda ugly, and it was set up way before we started using ELT, so it's possible we are just abusing Ember and/or dragdrop support. 

Basically, we have this function in a script tag in our index.html (this is the ugly part, not sure where this could go in a twiddle to reproduce most accurately)
```
      function dragInstrument(event) {
        event.dataTransfer.setData("iid", event.target.getAttribute("iid"));
      }
```

Then in some of our ELT tables we use a custom cell with a template that looks something like this:
```
<div iid="{{iid}}"
     draggable="true"
     ondragstart="dragInstrument(event)"
     class="draggable-cell">
  {{value}}
</div>
```
And `iid` is an attribute set on the cell component

Then of course we have drop targets and handlers for that but the errors that we're seeing are being thrown on drag so I don't think those come into play here. 

If you need to see any more code or have any suggestions as to how I can replicate this in a twiddle please let me know.
